[2024-01-05T03:52:08.798+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ds.sleep scheduled__2021-06-23T00:00:00+00:00 [queued]>
[2024-01-05T03:52:08.832+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ds.sleep scheduled__2021-06-23T00:00:00+00:00 [queued]>
[2024-01-05T03:52:08.836+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-01-05T03:52:08.898+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): sleep> on 2021-06-23 00:00:00+00:00
[2024-01-05T03:52:08.936+0000] {standard_task_runner.py:60} INFO - Started process 225 to run task
[2024-01-05T03:52:08.944+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ds', 'sleep', 'scheduled__2021-06-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpzzjbof55']
[2024-01-05T03:52:08.955+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask sleep
[2024-01-05T03:52:09.218+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ds.sleep scheduled__2021-06-23T00:00:00+00:00 [running]> on host fed638a2c175
[2024-01-05T03:52:09.391+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thangnch@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ds' AIRFLOW_CTX_TASK_ID='sleep' AIRFLOW_CTX_EXECUTION_DATE='2021-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-06-23T00:00:00+00:00'
[2024-01-05T03:52:09.411+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-05T03:52:09.415+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2024-01-05T03:52:09.454+0000] {subprocess.py:86} INFO - Output:
[2024-01-05T03:52:14.474+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-05T03:52:14.517+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_ds, task_id=sleep, execution_date=20210623T000000, start_date=20240105T035208, end_date=20240105T035214
[2024-01-05T03:52:14.572+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T03:52:14.590+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-01-08T04:50:51.521+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ds.sleep scheduled__2021-06-23T00:00:00+00:00 [queued]>
[2024-01-08T04:50:51.536+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ds.sleep scheduled__2021-06-23T00:00:00+00:00 [queued]>
[2024-01-08T04:50:51.538+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-01-08T04:50:51.555+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): sleep> on 2021-06-23 00:00:00+00:00
[2024-01-08T04:50:51.570+0000] {standard_task_runner.py:60} INFO - Started process 254 to run task
[2024-01-08T04:50:51.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ds', 'sleep', 'scheduled__2021-06-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpuu4t1f_g']
[2024-01-08T04:50:51.582+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask sleep
[2024-01-08T04:50:51.774+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ds.sleep scheduled__2021-06-23T00:00:00+00:00 [running]> on host 71a034ea89ba
[2024-01-08T04:50:52.108+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thangnch@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ds' AIRFLOW_CTX_TASK_ID='sleep' AIRFLOW_CTX_EXECUTION_DATE='2021-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-06-23T00:00:00+00:00'
[2024-01-08T04:50:52.131+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T04:50:52.140+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/index_data/index_to_es.py']
[2024-01-08T04:50:52.174+0000] {subprocess.py:86} INFO - Output:
[2024-01-08T04:50:52.248+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/dags/index_data/index_to_es.py': [Errno 2] No such file or directory
[2024-01-08T04:50:52.255+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-01-08T04:50:52.278+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-01-08T04:50:52.300+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ds, task_id=sleep, execution_date=20210623T000000, start_date=20240108T045051, end_date=20240108T045052
[2024-01-08T04:50:52.348+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-01-08T04:50:52.350+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-08T04:50:52.353+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-08T04:50:52.377+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-08T04:50:52.378+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-08T04:50:52.382+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['thangnch@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2335, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2500, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2517, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2947, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-08T04:50:52.423+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task sleep (Bash command failed. The command returned a non-zero exit code 2.; 254)
[2024-01-08T04:50:52.461+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T04:50:52.556+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
