[2024-01-08T05:12:26.128+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ds.send_email_task manual__2024-01-08T05:11:22.861772+00:00 [queued]>
[2024-01-08T05:12:26.136+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ds.send_email_task manual__2024-01-08T05:11:22.861772+00:00 [queued]>
[2024-01-08T05:12:26.137+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-08T05:12:26.147+0000] {taskinstance.py:2192} INFO - Executing <Task(EmailOperator): send_email_task> on 2024-01-08 05:11:22.861772+00:00
[2024-01-08T05:12:26.152+0000] {standard_task_runner.py:60} INFO - Started process 599 to run task
[2024-01-08T05:12:26.154+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ds', 'send_email_task', 'manual__2024-01-08T05:11:22.861772+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpg9wdkfx2']
[2024-01-08T05:12:26.157+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask send_email_task
[2024-01-08T05:12:26.190+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ds.send_email_task manual__2024-01-08T05:11:22.861772+00:00 [running]> on host 71a034ea89ba
[2024-01-08T05:12:26.236+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='cuongthanhhk@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ds' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T05:11:22.861772+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-08T05:11:22.861772+00:00'
[2024-01-08T05:12:26.245+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-01-08T05:12:26.247+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-08T05:12:26.248+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-08T05:12:26.251+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-08T05:12:26.258+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_ds, task_id=send_email_task, execution_date=20240108T051122, start_date=20240108T051226, end_date=20240108T051226
[2024-01-08T05:12:26.268+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task send_email_task ([Errno 99] Cannot assign requested address; 599)
[2024-01-08T05:12:26.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T05:12:26.299+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
