[2024-01-05T04:28:22.213+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: thangnc_dag01a.crawl_data manual__2024-01-05T04:28:19.989201+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
