[2024-01-05T04:20:34.574+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: data_ds.print_date manual__2024-01-05T04:19:24.409955+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-01-05T04:21:09.917+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: data_ds.print_date manual__2024-01-05T04:19:24.409955+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
