[2024-01-06T01:20:14.916+0000] {processor.py:161} INFO - Started process (PID=39347) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:20:14.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T01:20:14.921+0000] {logging_mixin.py:188} INFO - [2024-01-06T01:20:14.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:20:15.005+0000] {logging_mixin.py:188} INFO - [2024-01-06T01:20:15.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T01:20:15.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:20:15.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.110 seconds
[2024-01-06T01:47:34.215+0000] {processor.py:161} INFO - Started process (PID=39405) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:47:34.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T01:47:34.220+0000] {logging_mixin.py:188} INFO - [2024-01-06T01:47:34.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:47:34.309+0000] {logging_mixin.py:188} INFO - [2024-01-06T01:47:34.307+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T01:47:34.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:47:34.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.118 seconds
[2024-01-06T01:48:04.827+0000] {processor.py:161} INFO - Started process (PID=39463) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:48:04.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T01:48:04.832+0000] {logging_mixin.py:188} INFO - [2024-01-06T01:48:04.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:48:04.893+0000] {logging_mixin.py:188} INFO - [2024-01-06T01:48:04.892+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T01:48:04.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T01:48:04.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.086 seconds
[2024-01-06T02:05:26.272+0000] {processor.py:161} INFO - Started process (PID=39521) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:05:26.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:05:26.277+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:05:26.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:05:26.346+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:05:26.344+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:05:26.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:05:26.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.094 seconds
[2024-01-06T02:16:25.857+0000] {processor.py:161} INFO - Started process (PID=39579) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:16:25.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:16:25.864+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:16:25.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:16:25.954+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:16:25.951+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:16:25.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:16:25.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.118 seconds
[2024-01-06T02:16:56.188+0000] {processor.py:161} INFO - Started process (PID=39637) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:16:56.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:16:56.256+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:16:56.253+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:16:57.093+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:16:57.042+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:16:57.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:16:57.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 1.258 seconds
[2024-01-06T02:17:28.404+0000] {processor.py:161} INFO - Started process (PID=39696) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:17:28.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:17:28.409+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:17:28.409+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:17:28.478+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:17:28.476+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:17:28.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:17:28.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.096 seconds
[2024-01-06T02:17:58.947+0000] {processor.py:161} INFO - Started process (PID=39754) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:17:58.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:17:58.952+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:17:58.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:17:59.023+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:17:59.020+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:17:59.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:17:59.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.098 seconds
[2024-01-06T02:18:29.363+0000] {processor.py:161} INFO - Started process (PID=39812) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:18:29.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:18:29.371+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:18:29.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:18:29.453+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:18:29.450+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:18:29.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:18:29.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.114 seconds
[2024-01-06T02:19:00.368+0000] {processor.py:161} INFO - Started process (PID=39871) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:19:00.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:19:00.376+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:19:00.375+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:19:00.567+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:19:00.537+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:19:00.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:19:00.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.632 seconds
[2024-01-06T02:19:31.834+0000] {processor.py:161} INFO - Started process (PID=39929) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:19:31.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:19:31.843+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:19:31.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:19:31.968+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:19:31.956+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:19:31.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:19:31.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.181 seconds
[2024-01-06T02:20:02.329+0000] {processor.py:161} INFO - Started process (PID=39987) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:20:02.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:20:02.334+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:20:02.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:20:02.423+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:20:02.420+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:20:02.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:20:02.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.122 seconds
[2024-01-06T02:20:32.765+0000] {processor.py:161} INFO - Started process (PID=40045) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:20:32.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:20:32.770+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:20:32.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:20:32.838+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:20:32.836+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:20:32.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:20:32.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.097 seconds
[2024-01-06T02:21:03.332+0000] {processor.py:161} INFO - Started process (PID=40103) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:21:03.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:21:03.338+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:21:03.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:21:03.421+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:21:03.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:21:03.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:21:03.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.119 seconds
[2024-01-06T02:21:34.356+0000] {processor.py:161} INFO - Started process (PID=40161) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:21:34.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:21:34.367+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:21:34.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:21:34.440+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:21:34.438+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:21:34.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:21:34.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.114 seconds
[2024-01-06T02:22:04.727+0000] {processor.py:161} INFO - Started process (PID=40219) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:22:04.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:22:04.765+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:22:04.764+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:22:05.136+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:22:05.131+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:22:05.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:22:05.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.495 seconds
[2024-01-06T02:22:35.579+0000] {processor.py:161} INFO - Started process (PID=40277) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:22:35.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:22:35.586+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:22:35.586+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:22:35.677+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:22:35.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:22:35.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:22:35.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.119 seconds
[2024-01-06T02:23:06.270+0000] {processor.py:161} INFO - Started process (PID=40335) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:23:06.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:23:06.276+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:23:06.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:23:06.369+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:23:06.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:23:06.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:23:06.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.119 seconds
[2024-01-06T02:23:37.053+0000] {processor.py:161} INFO - Started process (PID=40393) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:23:37.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:23:37.076+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:23:37.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:23:37.186+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:23:37.184+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:23:37.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:23:37.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.158 seconds
[2024-01-06T02:24:07.302+0000] {processor.py:161} INFO - Started process (PID=40451) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:24:07.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:24:07.311+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:24:07.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:24:07.392+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:24:07.390+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:24:07.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:24:07.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.113 seconds
[2024-01-06T02:24:37.849+0000] {processor.py:161} INFO - Started process (PID=40509) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:24:37.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:24:37.856+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:24:37.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:24:37.943+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:24:37.941+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:24:37.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:24:37.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.114 seconds
[2024-01-06T02:25:08.404+0000] {processor.py:161} INFO - Started process (PID=40567) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:25:08.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:25:08.412+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:25:08.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:25:08.547+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:25:08.544+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:25:08.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:25:08.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.171 seconds
[2024-01-06T02:25:38.726+0000] {processor.py:161} INFO - Started process (PID=40625) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:25:38.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:25:38.731+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:25:38.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:25:38.810+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:25:38.808+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:25:38.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:25:38.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.104 seconds
[2024-01-06T02:26:09.469+0000] {processor.py:161} INFO - Started process (PID=40683) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:26:09.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:26:09.475+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:26:09.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:26:09.551+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:26:09.549+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:26:09.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:26:09.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.104 seconds
[2024-01-06T02:26:40.081+0000] {processor.py:161} INFO - Started process (PID=40741) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:26:40.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:26:40.087+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:26:40.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:26:40.162+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:26:40.160+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:26:40.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:26:40.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.100 seconds
[2024-01-06T02:27:10.878+0000] {processor.py:161} INFO - Started process (PID=40799) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:27:10.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:27:10.885+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:27:10.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:27:11.000+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:27:10.997+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:27:11.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:27:11.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.159 seconds
[2024-01-06T02:27:41.450+0000] {processor.py:161} INFO - Started process (PID=40857) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:27:41.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:27:41.456+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:27:41.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:27:41.556+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:27:41.554+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:27:41.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:27:41.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.127 seconds
[2024-01-06T02:28:12.373+0000] {processor.py:161} INFO - Started process (PID=40915) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:28:12.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:28:12.380+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:28:12.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:28:12.466+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:28:12.464+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:28:12.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:28:12.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.112 seconds
[2024-01-06T02:28:42.922+0000] {processor.py:161} INFO - Started process (PID=40973) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:28:42.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:28:42.928+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:28:42.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:28:42.995+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:28:42.992+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:28:42.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:28:43.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.095 seconds
[2024-01-06T02:29:13.537+0000] {processor.py:161} INFO - Started process (PID=41031) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:29:13.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:29:13.548+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:29:13.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:29:13.667+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:29:13.664+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:29:13.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:29:13.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.155 seconds
[2024-01-06T02:29:43.881+0000] {processor.py:161} INFO - Started process (PID=41089) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:29:43.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:29:43.891+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:29:43.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:29:44.013+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:29:44.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:29:44.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:29:44.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.160 seconds
[2024-01-06T02:30:14.720+0000] {processor.py:161} INFO - Started process (PID=41148) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:30:14.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:30:14.726+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:30:14.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:30:14.818+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:30:14.816+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:30:14.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:30:14.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.118 seconds
[2024-01-06T02:30:45.367+0000] {processor.py:161} INFO - Started process (PID=41206) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:30:45.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:30:45.374+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:30:45.374+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:30:45.466+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:30:45.463+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:30:45.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:30:45.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.120 seconds
[2024-01-06T02:31:16.011+0000] {processor.py:161} INFO - Started process (PID=41264) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:31:16.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:31:16.016+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:31:16.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:31:16.085+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:31:16.084+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:31:16.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:31:16.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.095 seconds
[2024-01-06T02:31:46.531+0000] {processor.py:161} INFO - Started process (PID=41322) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:31:46.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:31:46.536+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:31:46.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:31:46.610+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:31:46.608+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:31:46.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:31:46.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.104 seconds
[2024-01-06T02:32:16.802+0000] {processor.py:161} INFO - Started process (PID=41380) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:32:16.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:32:16.809+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:32:16.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:32:16.878+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:32:16.876+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:32:16.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:32:16.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.094 seconds
[2024-01-06T02:32:47.138+0000] {processor.py:161} INFO - Started process (PID=41438) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:32:47.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:32:47.147+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:32:47.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:32:47.217+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:32:47.214+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:32:47.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:32:47.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.109 seconds
[2024-01-06T02:33:17.814+0000] {processor.py:161} INFO - Started process (PID=41495) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:33:17.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:33:17.844+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:33:17.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:33:18.176+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:33:18.158+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:33:18.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:33:18.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.457 seconds
[2024-01-06T02:33:55.082+0000] {processor.py:161} INFO - Started process (PID=41558) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:33:55.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:33:55.195+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:33:55.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:33:56.188+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:33:56.161+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:33:56.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:33:56.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 1.441 seconds
[2024-01-06T02:34:26.951+0000] {processor.py:161} INFO - Started process (PID=41614) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:34:26.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:34:26.963+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:34:26.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:34:27.053+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:34:27.051+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:34:27.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:34:27.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.143 seconds
[2024-01-06T02:34:57.646+0000] {processor.py:161} INFO - Started process (PID=41671) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:34:57.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:34:57.650+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:34:57.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:34:57.765+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:34:57.761+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:34:57.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:34:57.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.158 seconds
[2024-01-06T02:35:28.429+0000] {processor.py:161} INFO - Started process (PID=41729) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:35:28.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:35:28.439+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:35:28.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:35:28.535+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:35:28.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:35:28.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:35:28.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.138 seconds
[2024-01-06T02:35:58.632+0000] {processor.py:161} INFO - Started process (PID=41787) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:35:58.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:35:58.640+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:35:58.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:35:58.712+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:35:58.710+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:35:58.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:35:58.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.102 seconds
[2024-01-06T02:36:29.061+0000] {processor.py:161} INFO - Started process (PID=41845) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:36:29.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:36:29.067+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:36:29.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:36:29.148+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:36:29.146+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:36:29.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:36:29.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.109 seconds
[2024-01-06T02:36:59.304+0000] {processor.py:161} INFO - Started process (PID=41903) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:36:59.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:36:59.312+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:36:59.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:36:59.391+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:36:59.389+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:36:59.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:36:59.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.106 seconds
[2024-01-06T02:37:29.456+0000] {processor.py:161} INFO - Started process (PID=41961) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:37:29.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:37:29.460+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:37:29.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:37:29.533+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:37:29.531+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:37:29.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:37:29.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.096 seconds
[2024-01-06T02:37:59.877+0000] {processor.py:161} INFO - Started process (PID=42018) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:37:59.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:37:59.885+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:37:59.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:37:59.981+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:37:59.979+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:37:59.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:37:59.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.127 seconds
[2024-01-06T02:38:30.209+0000] {processor.py:161} INFO - Started process (PID=42076) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:38:30.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:38:30.214+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:38:30.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:38:30.291+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:38:30.289+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:38:30.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:38:30.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.107 seconds
[2024-01-06T02:39:00.664+0000] {processor.py:161} INFO - Started process (PID=42133) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:39:00.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:39:00.670+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:39:00.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:39:00.753+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:39:00.751+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:39:00.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:39:00.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.107 seconds
[2024-01-06T02:39:31.492+0000] {processor.py:161} INFO - Started process (PID=42190) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:39:31.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:39:31.498+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:39:31.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:39:31.596+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:39:31.593+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:39:31.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:39:31.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.124 seconds
[2024-01-06T02:40:01.817+0000] {processor.py:161} INFO - Started process (PID=42249) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:40:01.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:40:01.826+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:40:01.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:40:01.906+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:40:01.904+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:40:01.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:40:01.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.112 seconds
[2024-01-06T02:40:32.050+0000] {processor.py:161} INFO - Started process (PID=42308) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:40:32.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:40:32.063+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:40:32.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:40:32.198+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:40:32.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:40:32.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:40:32.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.184 seconds
[2024-01-06T02:41:03.131+0000] {processor.py:161} INFO - Started process (PID=42366) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:41:03.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:41:03.139+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:41:03.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:41:03.210+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:41:03.209+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:41:03.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:41:03.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.100 seconds
[2024-01-06T02:41:33.993+0000] {processor.py:161} INFO - Started process (PID=42424) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:41:33.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:41:33.999+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:41:33.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:41:34.073+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:41:34.070+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:41:34.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:41:34.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.098 seconds
[2024-01-06T02:42:04.174+0000] {processor.py:161} INFO - Started process (PID=42481) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:42:04.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:42:04.179+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:42:04.179+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:42:04.245+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:42:04.243+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:42:04.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:42:04.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.090 seconds
[2024-01-06T02:42:34.339+0000] {processor.py:161} INFO - Started process (PID=42539) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:42:34.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:42:34.346+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:42:34.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:42:34.412+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:42:34.409+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:42:34.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:42:34.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.092 seconds
[2024-01-06T02:43:04.528+0000] {processor.py:161} INFO - Started process (PID=42597) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:43:04.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:43:04.540+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:43:04.540+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:43:04.673+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:43:04.670+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:43:04.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:43:04.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.186 seconds
[2024-01-06T02:43:34.878+0000] {processor.py:161} INFO - Started process (PID=42655) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:43:34.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:43:34.884+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:43:34.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:43:34.956+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:43:34.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:43:34.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:43:34.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.103 seconds
[2024-01-06T02:44:05.185+0000] {processor.py:161} INFO - Started process (PID=42713) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:44:05.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:44:05.192+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:44:05.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:44:05.267+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:44:05.265+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:44:05.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:44:05.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.106 seconds
[2024-01-06T02:44:35.345+0000] {processor.py:161} INFO - Started process (PID=42771) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:44:35.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:44:35.352+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:44:35.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:44:35.425+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:44:35.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:44:35.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:44:35.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.098 seconds
[2024-01-06T02:45:05.702+0000] {processor.py:161} INFO - Started process (PID=42829) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:45:05.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:45:05.709+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:45:05.708+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:45:05.777+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:45:05.776+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:45:05.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:45:05.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.099 seconds
[2024-01-06T02:45:35.853+0000] {processor.py:161} INFO - Started process (PID=42887) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:45:35.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:45:35.862+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:45:35.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:45:35.941+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:45:35.939+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:45:35.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:45:35.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.109 seconds
[2024-01-06T02:46:06.116+0000] {processor.py:161} INFO - Started process (PID=42945) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:46:06.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:46:06.123+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:46:06.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:46:06.198+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:46:06.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:46:06.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:46:06.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.102 seconds
[2024-01-06T02:46:36.700+0000] {processor.py:161} INFO - Started process (PID=43003) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:46:36.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:46:36.705+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:46:36.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:46:36.777+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:46:36.775+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:46:36.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:46:36.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.093 seconds
[2024-01-06T02:47:06.969+0000] {processor.py:161} INFO - Started process (PID=43061) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:47:06.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:47:06.975+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:47:06.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:47:07.061+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:47:07.059+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:47:07.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:47:07.101+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.138 seconds
[2024-01-06T02:47:37.518+0000] {processor.py:161} INFO - Started process (PID=43119) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:47:37.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:47:37.529+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:47:37.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:47:37.618+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:47:37.615+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:47:37.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:47:37.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.123 seconds
[2024-01-06T02:48:07.818+0000] {processor.py:161} INFO - Started process (PID=43177) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:48:07.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:48:07.823+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:48:07.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:48:07.902+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:48:07.900+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:48:07.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:48:07.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.101 seconds
[2024-01-06T02:48:38.432+0000] {processor.py:161} INFO - Started process (PID=43235) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:48:38.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:48:38.545+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:48:38.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:48:38.831+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:48:38.826+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:48:38.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:48:38.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.458 seconds
[2024-01-06T02:49:24.635+0000] {processor.py:161} INFO - Started process (PID=43292) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:49:24.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:49:24.639+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:49:24.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:49:24.738+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:49:24.736+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:49:24.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:49:24.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.123 seconds
[2024-01-06T02:49:55.116+0000] {processor.py:161} INFO - Started process (PID=43337) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:49:55.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:49:55.123+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:49:55.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:49:55.236+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:49:55.232+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:49:55.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:49:55.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.180 seconds
[2024-01-06T02:50:25.505+0000] {processor.py:161} INFO - Started process (PID=43389) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:50:25.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:50:25.514+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:50:25.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:50:25.616+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:50:25.614+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:50:25.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:50:25.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.133 seconds
[2024-01-06T02:50:56.345+0000] {processor.py:161} INFO - Started process (PID=43447) to work on /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:50:56.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_data_to_es.py for tasks to queue
[2024-01-06T02:50:56.351+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:50:56.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:50:56.434+0000] {logging_mixin.py:188} INFO - [2024-01-06T02:50:56.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/index_data/index_data_to_es.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/index_data/index_data_to_es.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[2024-01-06T02:50:56.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/index_data/index_data_to_es.py
[2024-01-06T02:50:56.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/index_data/index_data_to_es.py took 0.112 seconds
